pub mod ext_workspace;
pub mod foreign_toplevel;
pub mod gamma_control;
pub mod image_capture_source;
pub mod image_copy_capture;
pub mod output_management;
pub mod output_power;
pub mod screencopy;
pub mod virtual_keyboard;
